spring:
  config:
      import: "optional:file:.env[.properties]"
  application:
    name: i18nSpreadsheetSync

google:
  sheets:
    spreadsheet-id: ${SPREAD_SHEET_ID}
    sheet-name: 'Sheet1'
    service-account-key-path: classpath:service-account-key.json
