spring:
  config:
      import: "optional:file:.env[.properties]"
  application:
    name: i18nSpreadsheetSync

google:
  sheets:
    serviceAccountKeyPath: classpath:service-account-key.json
    spreadsheet-id: ${SPREAD_SHEET_ID}
